name: CI for Remix App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies using npm or yarn
      - name: Install dependencies
        run: npm install

      # # Step 4: Run tests
      # - name: Run tests
      #   run: npm test

      # Step 5: Optionally, you can run type-checking if you're using TypeScript
      - name: Run TypeScript type-check
        run: npm run type-check
